version: '3.8'

services:
  animflix:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: animflix
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "8090:8090"
    environment:
      - PORT=3000
      - TORRSERVER_URL=http://127.0.0.1:8090
      - FFMPEG_HWACCEL=auto
      - VAAPI_DEVICE=/dev/dri/renderD128
      # - NYAA_URL=https://nyaa.si
      # - TMDB_API_KEY=your_key_optional
    # Accès matériel au GPU Intel/AMD pour transcodage ultra-rapide VAAPI (0% CPU)
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./cache:/app/cache
      - animflix_data:/root/.local/share/TorrServer

volumes:
  animflix_data:
